const mockProducts = [
    {
        id: 1,
        image: '/assets/iphone.png',
        name: 'VRB01 Virtual Reality Glasses',
        reviewCount: '(14)',
        basePrice: '$430.00',
        sellPrice: '$340.99',
    },
    {
        id: 2,
        image: '/assets/watch.png',
        name: 'Apple iPhone 14 128GB White',
        reviewCount: '(142)',
        basePrice: '$899.00',
        sellPrice: '$799.99',
    },
    {
        id: 3,
        image: '/assets/ipad.png',
        name: 'Smart Watch Series 7, White',
        reviewCount: '(64)',
        basePrice: '$450.00',
        sellPrice: '$429.00',
    },
    {
        id: 4,
        image: '/assets/airpods.png',
        name: 'Tablet Apple iPad Air M1',
        reviewCount: '(27)',
        basePrice: '$540.00',
        sellPrice: '$400.00',
    },
    {
        id: 5,
        image: '/assets/macbook.png',
        name: 'Laptop Apple MacBook Pro 13 M2',
        reviewCount: '(120)',
        basePrice: '$1540.00',
        sellPrice: '$1400.00',
    },
    {
        id: 5,
        image: '/assets/vr.png',
        name: 'VRB01 Virtual Reality Glasses',
        reviewCount: '(120)',
        basePrice: '$2540.00',
        sellPrice: '$2400.00',
    },
    {
        id: 6,
        image: '/assets/iphone.png',
        name: 'VRB01 Virtual Reality Glasses',
        reviewCount: '(14)',
        basePrice: '$430.00',
        sellPrice: '$340.99',
    },
    {
        id: 6,
        image: '/assets/watch.png',
        name: 'Apple iPhone 14 128GB White',
        reviewCount: '(142)',
        basePrice: '$899.00',
        sellPrice: '$799.99',
    },
    {
        id: 7,
        image: '/assets/ipad.png',
        name: 'Smart Watch Series 7, White',
        reviewCount: '(64)',
        basePrice: '$450.00',
        sellPrice: '$429.00',
    },
    {
        id: 8,
        image: '/assets/airpods.png',
        name: 'Tablet Apple iPad Air M1',
        reviewCount: '(27)',
        basePrice: '$540.00',
        sellPrice: '$400.00',
    },
    {
        id: 9,
        image: '/assets/macbook.png',
        name: 'Laptop Apple MacBook Pro 13 M2',
        reviewCount: '(120)',
        basePrice: '$1540.00',
        sellPrice: '$1400.00',
    },
    {
        id: 10,
        image: '/assets/vr.png',
        name: 'VRB01 Virtual Reality Glasses',
        reviewCount: '(120)',
        basePrice: '$2540.00',
        sellPrice: '$2400.00',
    },
];

export default mockProducts;
